### ISSUE TITLE
画像が正常に書き込まれず、毎回縦縞として描画されてしまう。

### ISSUE THREAD

**Issue by ghost** [3nni5/Macro-Create#1]
こちら再現率100％なのですが、改善方法などございましたらご教示ください。

環境
Windows10 Pro 64bit
Python 3.10.7
NX Macro Controller 2.07 Switchとの接続テスト済み
pip install asgiref Django image numpy Pillow pytz six sqlparse typing_extensions 済み

手順
1.320x120の2階調化したbmp画像(picture.bmp)を用意します。
2.任意の場所に保存された「main.py」を右クリック→「Edit with IDLE 3.10」を実行。
3.遷移後の「main.py」ウィンドウで「Run Module」を選択。
4.遷移後の「IDLE shell 3.10.7」ウィンドウにて以下の記述を確認。

Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

===================== RESTART: D:\Macro-Create-main\main.py ====================

5.出力された「macro.txt」の中身を確認する。
6.SwitchとNX Macro Controllerを接続し、手順5のマクロをコピー＆ペーストして実行。
7.4ドット程度の黒い縦線、1ドットの白い縦線が交互に描き込まれてしまい、1で準備した画像と異なる結果になる。

**Comment by 3nni5** [comment]
大変申し訳ございません。
只今立て込んでおり、対応が難しいです。
再現率100％とのことですので、暇ができ次第こちらの動作環境においても確認してみます。
正常に書き込まれない現象が発生する画像ファイル（bmpファイル）を送っていただけないでしょうか。
よろしくお願いします。

連絡先
Twitter DM: ＠Enn1z
mail: ennisland@protonmail.com

**Comment by 3nni5** [comment]
ご使用の画像(.bmpファイル)を確認いたしました．

どうやら画像が「モノクロビットマップ」ではなく「16色ビットマップ」になっているようです．以下の手順で確認および画像形式の変更をお願いします．（※画像を変更する前に元ファイルのバックアップを必ずお願いします．）

### 手順
1. picture.bmpを右クリック
2. 「編集」をクリック（ペイントが開ければOK）
3. 「ファイル」をクリック
4. 「名前を付けて保存」をクリック
5. 「ファイルの種類」から「モノクロビットマップ」を選択し保存

### 見分け方
画像をペイントで開いた際に，16色ビットマップとモノクロビットマップではカラーパレットが異なります．
モノクロビットマップでは漫画で使われるトーンのようなものがカラーパレットとしてセットされているはずです．

### モノクロビットマップでなければならない理由
このプログラムは個人用に作成した簡単なもののため，対応力が低く，モノクロビットマップのような2値しか存在し得ないものでなければ正しく動作しません．
ぜひご自身でプログラムを改良して，フォークして頂ければ幸いです！

**Comment by ghost** [comment]
ありがとうございます、早速確認したところ無事に描画が開始されました。
この度は迅速なご対応誠にありがとうございました。重ねてお礼申し上げます。
